# Generated by Django 3.0.3 on 2020-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systeminfo',
            name='eventviewer',
            field=models.CharField(choices=[('error', 'Error'), ('no error', 'No Error'), ('password reqired', 'Password Required'), ('power off', 'Power Off'), ('office 2016 licensing', 'office 2016 licensing')], max_length=100),
        ),
    ]
